apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: demo-app
  namespace: default
spec:
  routes:
    - kind: Rule
      match: Host(`demo.iulia.live`)
      priority: 10
      services:
        - name: demo-service
          port: 80
      middlewares:
        - name: demo-stripprefix    
  tls:
    certResolver: le